nbbang-sinchon/backend

build.gradle, src/main/java/nbbang/com/nbbang/domain/bbangpan/controller/BbangpanController.java, src/main/java/nbbang/com/nbbang/domain/bbangpan/dto/BbangpanDto.java, src/main/java/nbbang/com/nbbang/domain/bbangpan/dto/BbangpanGetResponseDto.java, src/main/java/nbbang/com/nbbang/domain/bbangpan/dto/MemberBbangpanDto.java, src/main/java/nbbang/com/nbbang/domain/member/domain/Member.java, src/main/java/nbbang/com/nbbang/domain/party/controller/ManyPartyController.java, src/main/java/nbbang/com/nbbang/domain/party/controller/PartyController.java, src/main/java/nbbang/com/nbbang/domain/party/dto/CreatePartyDto.java, src/main/java/nbbang/com/nbbang/domain/party/dto/PartyFindRequestDto.java, src/main/java/nbbang/com/nbbang/domain/party/dto/PartyFindResponseDto.java, src/main/java/nbbang/com/nbbang/domain/party/dto/PartyList.java, src/main/java/nbbang/com/nbbang/domain/party/dto/PartyReadResponseDto.java, src/main/java/nbbang/com/nbbang/domain/party/dto/PartyRequestDto.java
=> Feat : 파티, 빵판 API 추가

src/main/java/nbbang/com/nbbang/domain/bbangpan/controller/BbangpanController.java, src/main/java/nbbang/com/nbbang/domain/bbangpan/dto/BbangpanPriceChangeRequestDto.java, src/main/java/nbbang/com/nbbang/domain/bbangpan/dto/BbangpanStatusChangeRequestDto.java, src/main/java/nbbang/com/nbbang/domain/party/controller/ManyPartyController.java, src/main/java/nbbang/com/nbbang/domain/party/controller/PartyController.java, src/main/java/nbbang/com/nbbang/domain/party/domain/Party.java, src/main/java/nbbang/com/nbbang/global/response/DefaultRes.java, src/main/java/nbbang/com/nbbang/global/response/ResponseMessage.java
- 디폴트 Response 클래스를 추가하였습니다.
- 파티 API를 추가하였습니다. 기능적으로는 완료되었고 @Schema 명시 등 일부분 수정해야 합니다.
=> Fix : 디폴트 Response 클래스, 파티 API 추가

.gitignore, src/main/java/nbbang/com/nbbang/domain/member/dto/PlaceResponseDto.java, src/main/java/nbbang/com/nbbang/domain/party/controller/PartyController.java, src/main/java/nbbang/com/nbbang/domain/party/controller/PartyResponseDto.java, src/main/java/nbbang/com/nbbang/global/response/DefaultResponse.java
- Dto를 public으로 변경하였습니다.
- DefaultRes 클래스를 DefaultResponse 클래스로 변경하였습니다.
=> Refactor : Dto public으로 변경, 클래스 이름 변경

src/main/java/nbbang/com/nbbang/domain/bbangpan/controller/BbangpanController.java, src/main/java/nbbang/com/nbbang/domain/bbangpan/dto/BbangpanPriceChangeRequestDto.java, src/main/java/nbbang/com/nbbang/domain/bbangpan/dto/BbangpanStatusChangeRequestDto.java, src/main/java/nbbang/com/nbbang/domain/member/controller/MemberController.java, src/main/java/nbbang/com/nbbang/domain/party/controller/ManyPartyController.java, src/main/java/nbbang/com/nbbang/domain/party/controller/PartyController.java, src/main/java/nbbang/com/nbbang/domain/party/domain/Status.java, src/main/java/nbbang/com/nbbang/global/response/ObjectMaker.java, src/main/java/nbbang/com/nbbang/global/response/ResponseMessage.java, src/main/java/nbbang/com/nbbang/global/response/ResponseMessageBbangpan.java, src/main/java/nbbang/com/nbbang/global/response/ResponseMessageParty.java, src/main/java/nbbang/com/nbbang/global/response/StatusCode.java, src/main/resources/application.properties
- ResponseEntity를 도입해서 return할 때 상태 코드와 메시지도 전달되도록 수정하였습니다. 
- 자잘자잘한 오류도 수정하였습니다.
=> Refactor : ResponseEntity 도입

src/main/java/nbbang/com/nbbang/domain/party/controller/PartyController.java, src/main/java/nbbang/com/nbbang/domain/party/domain/Hashtag.java, src/main/java/nbbang/com/nbbang/domain/party/domain/Party.java, src/main/java/nbbang/com/nbbang/domain/party/domain/PartyHashtag.java, src/main/java/nbbang/com/nbbang/domain/party/repository/ManyPartyRepository.java, src/main/java/nbbang/com/nbbang/domain/party/service/ManyPartyService.java
- PartyHashtag 엔티티를 추가하였습니다.
- ManyPartyRepository와 ManyPartyService를 추가하였습니다.
=> PartyHashtag 추가, ManyParty 레포지토리와 서비스 추가

src/main/java/nbbang/com/nbbang/domain/party/controller/PartyController.java, src/main/java/nbbang/com/nbbang/domain/party/domain/Hashtag.java, src/main/java/nbbang/com/nbbang/domain/party/domain/PartyHashtag.java, src/main/java/nbbang/com/nbbang/domain/party/service/HashtagService.java, src/main/java/nbbang/com/nbbang/domain/party/service/PartyService.java
PartyHashtag 엔티티를 적용해서 Hashtag와 Party의 연관관계를 맺는 코드를 추가하였습니다.
=> Hashtag와 Party의 연관관계 매핑 추가

src/main/java/nbbang/com/nbbang/domain/party/dto/PartyFindRequestFilterDto.java, src/test/java/nbbang/com/nbbang/domain/party/repository/ManyPartyRepositoryTest.java
파티 리스트 조회 필터에 null-safety 를 추가하였고 테스트 케이스를 추가하였습니다
=> 파티 리스트 조회 필터 수정과 테스트 케이스 추가

src/main/java/nbbang/com/nbbang/SampleController.java, src/main/java/nbbang/com/nbbang/domain/member/controller/MemberController.java, src/main/java/nbbang/com/nbbang/domain/member/domain/Member.java, src/main/java/nbbang/com/nbbang/domain/member/dto/MemberResponseDto.java, src/main/java/nbbang/com/nbbang/domain/member/dto/MemberUpdateRequestDto.java, src/main/java/nbbang/com/nbbang/domain/member/dto/Place.java, src/main/java/nbbang/com/nbbang/domain/member/dto/PlaceResponseDto.java, src/main/java/nbbang/com/nbbang/domain/member/service/MemberService.java, src/main/java/nbbang/com/nbbang/domain/party/controller/ManyPartyController.java, src/main/java/nbbang/com/nbbang/domain/party/dto/PartyFindRequestDto.java, src/main/java/nbbang/com/nbbang/domain/party/dto/PartyFindRequestFilterDto.java, src/main/java/nbbang/com/nbbang/domain/party/repository/ManyPartyRepository.java, src/main/java/nbbang/com/nbbang/domain/party/repository/ManyPartyRepositorySupport.java, src/main/java/nbbang/com/nbbang/domain/party/repository/ManyPartyRepositorySupportImpl.java, src/main/java/nbbang/com/nbbang/domain/party/service/ManyPartyService.java, src/main/java/nbbang/com/nbbang/global/exception/MemberNotFoundException.java, src/main/java/nbbang/com/nbbang/global/support/test/MockDataCreator.java
- 파티 리스트 조회 필터를 구현하였습니다. 파티 위치, 모집 중인지, 제목 검색어로 필터링 할 수 있습니다.
- 로그인 기능을 제외한 회원 CRUD 기능을 추가하였습니다.
=> 파티 리스트 조회 필터, 회원 CRUD 

src/main/java/nbbang/com/nbbang/domain/party/controller/PartyController.java, src/main/java/nbbang/com/nbbang/global/exception/CustomIllegalArgumentException.java, src/main/java/nbbang/com/nbbang/global/exception/ErrorResponse.java, src/main/java/nbbang/com/nbbang/global/exception/FieldErrorInfo.java, src/main/java/nbbang/com/nbbang/global/exception/GlobalControllerAdvice.java, src/main/java/nbbang/com/nbbang/global/response/DefaultResponse.java, src/main/java/nbbang/com/nbbang/global/response/GlobalResponseMessage.java
Dto 필드 에러가 발생하면 response 데이터에 에러 정보가 전송됩니다.
=> 에러 메시지 전송 기능 추가

src/main/java/nbbang/com/nbbang/domain/party/controller/PartyController.java, src/main/java/nbbang/com/nbbang/domain/party/controller/PartyResponseMessage.java, src/main/java/nbbang/com/nbbang/domain/party/domain/Hashtag.java, src/main/java/nbbang/com/nbbang/domain/party/domain/Party.java, src/main/java/nbbang/com/nbbang/domain/party/domain/PartyHashtag.java, src/main/java/nbbang/com/nbbang/domain/party/dto/CreatePartyDto.java, src/main/java/nbbang/com/nbbang/domain/party/dto/PartyFindRequestDto.java, src/main/java/nbbang/com/nbbang/domain/party/dto/PartyFindResponseDto.java, src/main/java/nbbang/com/nbbang/domain/party/dto/PartyIdResponseDto.java, src/main/java/nbbang/com/nbbang/domain/party/dto/PartyReadResponseDto.java, src/main/java/nbbang/com/nbbang/domain/party/dto/PartyRequestDto.java, src/main/java/nbbang/com/nbbang/domain/party/dto/PartyUpdateServiceDto.java, src/main/java/nbbang/com/nbbang/domain/party/repository/HashtagRepository.java, src/main/java/nbbang/com/nbbang/domain/party/repository/PartyHashtagRepository.java, src/main/java/nbbang/com/nbbang/domain/party/service/HashtagService.java, src/main/java/nbbang/com/nbbang/domain/party/service/PartyService.java, src/test/java/nbbang/com/nbbang/domain/chat/service/repository/MessageRepositoryTest.java
해시태그를 생성, 수정, 조회, 삭제 할 수 있습니다.
=> 해시태그 CRUD 로직 구현

src/main/java/nbbang/com/nbbang/domain/party/controller/PartyController.java, src/main/java/nbbang/com/nbbang/domain/party/repository/PartyRepository.java, src/main/java/nbbang/com/nbbang/domain/party/repository/PartyRepositorySupport.java, src/main/java/nbbang/com/nbbang/domain/party/repository/PartyRepositorySupportImpl.java, src/main/java/nbbang/com/nbbang/domain/party/service/PartyService.java
- 파티 조회 시 주변 파티 목록에 요청한 파티는 보이지 않게 설정하였습니다. 
- 파티 삭제 API를 삭제하였습니다.
=> 파티 조회 수정, 파티 삭제 API 삭제

src/main/java/nbbang/com/nbbang/domain/bbangpan/domain/MemberParty.java, src/main/java/nbbang/com/nbbang/domain/bbangpan/repository/MemberPartyRepository.java, src/main/java/nbbang/com/nbbang/domain/chat/controller/ChatController.java, src/main/java/nbbang/com/nbbang/domain/chat/dto/ChatResponseDto.java, src/main/java/nbbang/com/nbbang/domain/chat/service/ChatService.java, src/main/java/nbbang/com/nbbang/domain/member/controller/MemberController.java, src/main/java/nbbang/com/nbbang/domain/member/controller/MemberDevelopController.java, src/main/java/nbbang/com/nbbang/domain/member/dto/MemberListResponseDto.java, src/main/java/nbbang/com/nbbang/domain/party/controller/ManyPartyController.java, src/main/java/nbbang/com/nbbang/domain/party/controller/PartyController.java, src/main/java/nbbang/com/nbbang/domain/party/domain/Party.java, src/main/java/nbbang/com/nbbang/domain/party/dto/MyClosedPartyListRequestDto.java, src/main/java/nbbang/com/nbbang/domain/party/dto/MyOnPartyListRequestDto.java, src/main/java/nbbang/com/nbbang/domain/party/dto/MyPartyListResponseDto.java, src/main/java/nbbang/com/nbbang/domain/party/dto/MyPartyResponseDto.java, src/main/java/nbbang/com/nbbang/domain/party/dto/PartyFindRequestFilterDto.java, src/main/java/nbbang/com/nbbang/domain/party/dto/PartyListRequestDto.java, src/main/java/nbbang/com/nbbang/domain/party/dto/PartyListRequestFilterDto.java, src/main/java/nbbang/com/nbbang/domain/party/dto/PartyListResponseDto.java, src/main/java/nbbang/com/nbbang/domain/party/repository/ManyPartyRepository.java, src/main/java/nbbang/com/nbbang/domain/party/repository/ManyPartyRepositorySupport.java, src/main/java/nbbang/com/nbbang/domain/party/repository/ManyPartyRepositorySupportImpl.java, src/main/java/nbbang/com/nbbang/domain/party/service/ManyPartyService.java, src/main/java/nbbang/com/nbbang/domain/party/service/PartyService.java, src/main/java/nbbang/com/nbbang/global/config/WebSocketConfig.java, src/main/java/nbbang/com/nbbang/global/support/test/MockDataCreator.java, src/test/java/nbbang/com/nbbang/domain/bbangpan/repository/MemberPartyRepositoryTest.java, src/test/java/nbbang/com/nbbang/domain/party/service/ManyPartyServiceTest.java, src/test/java/nbbang/com/nbbang/domain/party/service/PartyServiceTest.java, src/test/resources/application.properties
- 파티 리스트 조회하는 기능을 개선하였습니다.
- 나의 파티를 조회할 경우 api request 와 response 를 일반적인 조회와 다르게 만들었습니다.
- 테스트 데이터를 추가하였습니다.
- 파티 참여 / 탈퇴 관련한 버그를 수정하였습니다.
=> 파티 리스트 조회 기능 개선 및 버그 수정

src/test/resources/application.properties
테스트 설정 파일에 h2dialect를 추가하였습니다.
=> 테스트 h2 dialect 추가

appspec.yml
CodeDeploy Agent가 참고하여 배포할 수 있는 appspec.yml 파일을 추가하였습니다.
=> appspec.yml 추가

appspec.yml
CodeDeploy Agent가 참고하여 배포할 수 있는 appspec.yml 파일을 변경하였습니다.
=> appspec.yml 변경

appspec.yml
appspec.yml 파일의 permission을 root로 설정하였습니다.
=> permission root로 설정

src/main/java/nbbang/com/nbbang/domain/party/controller/PartyController.java, src/main/java/nbbang/com/nbbang/domain/party/controller/PartyResponseMessage.java, src/main/java/nbbang/com/nbbang/domain/party/dto/single/request/PartyRequestDto.java, src/main/java/nbbang/com/nbbang/domain/party/dto/single/response/PartyReadResponseDto.java, src/main/java/nbbang/com/nbbang/domain/party/validation/HashtagNumberAndDuplicateValidator.java, src/main/java/nbbang/com/nbbang/domain/party/validation/PartyCreateGroup.java, src/main/java/nbbang/com/nbbang/global/error/GlobalControllerAdvice.java, src/main/java/nbbang/com/nbbang/global/error/GlobalErrorResponseMessage.java, src/main/java/nbbang/com/nbbang/global/response/StatusCode.java, src/main/java/nbbang/com/nbbang/global/security/jwt/JwtService.java, src/main/resources/application.properties, src/test/java/nbbang/com/nbbang/domain/party/controller/ControllerTestUtil.java, src/test/java/nbbang/com/nbbang/domain/party/controller/SinglePartyApiTest.java
- update에도 validation이 작동합니다.
- 파티 조회 시 member 정보는 전달하지 않습니다. 
- API 오류 검정 테스트 코드를 작성하였습니다.
=> 파티 CRUD 오류 수정

src/main/java/nbbang/com/nbbang/domain/party/controller/ManyPartyController.java, src/main/java/nbbang/com/nbbang/domain/party/dto/PartyFindResponseDto.java, src/main/java/nbbang/com/nbbang/domain/party/repository/ManyPartyRepositorySupportImpl.java, src/main/java/nbbang/com/nbbang/global/config/WebMvcConfig.java, src/main/java/nbbang/com/nbbang/global/interceptor/LoginInterceptor.java, src/main/java/nbbang/com/nbbang/global/security/LoginRedirectionFilter.java, src/main/java/nbbang/com/nbbang/global/security/OAuth2AuthenticationSuccessHandler.java, src/main/java/nbbang/com/nbbang/global/security/RequestLogUtils.java, src/main/java/nbbang/com/nbbang/global/security/SecurityConfig.java, src/main/java/nbbang/com/nbbang/global/security/TokenAuthenticationFilter.java
- 로그인 필터 제외 대상을 추가하였습니다.
- redirect 버그를 수정하였습니다
=> 로그인 필터 제외 대상 추가, redirect 버그 수정

src/main/java/nbbang/com/nbbang/global/socket/LoginHandShakeInterceptor.java, src/main/java/nbbang/com/nbbang/global/socket/StompChannelInterceptor.java, src/main/java/nbbang/com/nbbang/global/socket/StompWebSocketMessageBrokerConfig.java
소켓 handshake 에서 current member 에 id 가 담기지 않는 오류를 수정하였습니다.
=> 소켓 로그인 오류 수정

src/main/java/nbbang/com/nbbang/global/security/OAuth2AuthenticationSuccessHandler.java, src/main/java/nbbang/com/nbbang/global/security/SecurityConfig.java, src/main/java/nbbang/com/nbbang/global/socket/LoginHandshakeInterceptor.java, src/main/java/nbbang/com/nbbang/global/socket/StompChannelInterceptor.java, src/main/java/nbbang/com/nbbang/global/socket/StompWebSocketMessageBrokerConfig.java
로그인 인증을 구현함에 따라 소켓에 인증 정보를 전달하는 방식을 변경하였습니다.
=> 소켓 인증 정보 추가하기

src/main/java/nbbang/com/nbbang/SampleController.java, src/main/java/nbbang/com/nbbang/domain/chat/dto/ChatResponseDto.java, src/main/java/nbbang/com/nbbang/domain/chat/dto/ChatSendListResponseDto.java, src/main/java/nbbang/com/nbbang/domain/chat/dto/message/ChatSendResponseDto.java, src/main/java/nbbang/com/nbbang/domain/chat/service/ChatService.java, src/main/java/nbbang/com/nbbang/domain/chat/service/MessageService.java, src/main/java/nbbang/com/nbbang/domain/party/service/PartyMemberService.java, src/main/java/nbbang/com/nbbang/global/socket/ChatRoomService.java, src/main/java/nbbang/com/nbbang/global/socket/SocketAPI.java, src/main/java/nbbang/com/nbbang/global/socket/SocketSender.java, src/main/java/nbbang/com/nbbang/global/socket/StompChannelInterceptor.java, src/main/java/nbbang/com/nbbang/global/socket/redisPubSub/RedisPublisher.java, src/main/java/nbbang/com/nbbang/global/socket/redisPubSub/RedisSocketConfig.java, src/main/java/nbbang/com/nbbang/global/socket/redisPubSub/RedisSubscriber.java, src/main/java/nbbang/com/nbbang/global/socket/redisPubSub/RedisTopicRepository.java, src/main/java/nbbang/com/nbbang/global/validator/PartyMemberValidator.java, src/main/java/nbbang/com/nbbang/global/validator/PartyMemberValidatorById.java, src/test/java/nbbang/com/nbbang/domain/chat/service/ChatReadTest.java, src/test/java/nbbang/com/nbbang/domain/member/controller/MyPartiesControllerTest.java, src/test/java/nbbang/com/nbbang/global/validator/PartyMemberPartyMemberValidatorTestById.java
채팅 unsubscribe시 destination을 id 값에서 찾아서 에러를 수정합니다.
=> 채팅 unsubscribe 에러 수정

src/main/java/nbbang/com/nbbang/global/security/CustomOAuth2MemberService.java, src/main/java/nbbang/com/nbbang/global/security/LoginController.java, src/main/java/nbbang/com/nbbang/global/security/LogoutService.java, src/main/java/nbbang/com/nbbang/global/security/OAuthAttributes.java, src/main/java/nbbang/com/nbbang/global/security/SecurityConfig.java
- 카카오, 네이버 로그인 구현하였습니다.
- 스웨거가 인증을 필요로하는 오류를 수정하였습니다.
- 로그아웃 기능을 개선하였습니다.
=> 카카오, 네이버 로그인 구현, 오류 수정

src/main/java/nbbang/com/nbbang/global/socket/ChatRoomService.java
@transactional을 붙이지 않아 읽지 않음이 반영되지 않는 문제를 해결하였습니다.
=> 나갈 때 읽지 않음이 반영되는 문제 해결

src/main/java/nbbang/com/nbbang/domain/bbangpan/repository/PartyMemberRepository.java, src/main/java/nbbang/com/nbbang/domain/bbangpan/repository/PartyMemberRepositorySupport.java, src/main/java/nbbang/com/nbbang/domain/bbangpan/repository/PartyMemberRepositorySupportImpl.java, src/main/java/nbbang/com/nbbang/domain/member/controller/MemberController.java, src/main/java/nbbang/com/nbbang/domain/member/domain/Member.java, src/main/java/nbbang/com/nbbang/domain/member/dto/MemberResponseDto.java, src/main/java/nbbang/com/nbbang/domain/member/service/MemberService.java, src/main/java/nbbang/com/nbbang/domain/party/service/PartyMemberService.java, src/test/java/nbbang/com/nbbang/domain/member/service/MemberServiceTest.java
api GET /members를 호출하면 멤버가 읽지 않은 채팅이 있는지 정보를 제공하여 알람을 띄우는 것을 돕습니다.
=> 멤버가 읽지 않은 채팅이 있는지 정보 제공

src/main/java/nbbang/com/nbbang/domain/chat/controller/ChatRoomController.java, src/main/java/nbbang/com/nbbang/domain/chat/repository/MessageRepository.java, src/main/java/nbbang/com/nbbang/domain/chat/repository/MessageRepositorySupport.java, src/main/java/nbbang/com/nbbang/domain/chat/repository/MessageRepositorySupportImpl.java, src/main/java/nbbang/com/nbbang/domain/chat/service/ChatService.java, src/main/java/nbbang/com/nbbang/domain/member/controller/MyPartiesController.java, src/main/java/nbbang/com/nbbang/domain/party/service/PartyMemberService.java, src/main/java/nbbang/com/nbbang/global/socket/ChatRoomService.java, src/test/java/nbbang/com/nbbang/domain/chat/service/ChatServiceTest.java, src/test/java/nbbang/com/nbbang/domain/party/service/PartyMemberServiceTest.java
- 파티 탈퇴 이후 소켓을 unsubscribe하면 NPE가 떠서 Optional 코드를 추가합니다.
=> 파티 탈퇴 이후 소켓 unsubscribe 에러 처리

src/main/java/nbbang/com/nbbang/domain/chat/dto/ChatResponseDto.java, src/main/java/nbbang/com/nbbang/global/security/JwtAuthenticationFilter.java, src/main/java/nbbang/com/nbbang/global/security/OAuthAttributes.java, src/main/resources/application.properties
- 채팅방 조회시 위시리스트 여부를 포함합니다.
- 배포 환경인지 로컬 환경인지 apploication properties 파일을 이용하여 구분합니다.
=> 채팅방 위시리스트 추가, 배포 설정 추가

src/main/java/nbbang/com/nbbang/domain/chat/controller/ChatRoomController.java, src/main/java/nbbang/com/nbbang/global/socket/ChatRoomService.java, src/main/java/nbbang/com/nbbang/global/socket/repository/MemorySocketPartyMemberRepository.java, src/main/java/nbbang/com/nbbang/global/socket/repository/RedisSocketPartyMemberRepository.java, src/main/java/nbbang/com/nbbang/global/socket/repository/SocketPartyMemberRepository.java, src/main/java/nbbang/com/nbbang/global/socket/service/SocketPartyMemberService.java, src/test/java/nbbang/com/nbbang/domain/chat/service/ChatReadTest.java, src/test/java/nbbang/com/nbbang/domain/member/service/MemberServiceTest.java
=> 여러 브라우저에서 채팅방에 접속하면 읽은 수가 줄어드는 문제 해결 

src/main/java/nbbang/com/nbbang/domain/chat/service/ChatService.java, src/main/java/nbbang/com/nbbang/domain/chat/service/MessageService.java, src/main/java/nbbang/com/nbbang/domain/party/controller/PartyWishlistController.java, src/main/java/nbbang/com/nbbang/domain/party/domain/Party.java, src/main/java/nbbang/com/nbbang/domain/party/repository/PartyRepositorySupport.java, src/main/java/nbbang/com/nbbang/domain/party/repository/PartyRepositorySupportImpl.java, src/main/java/nbbang/com/nbbang/domain/party/repository/PartyWishlistRepository.java, src/main/java/nbbang/com/nbbang/domain/party/service/PartyService.java, src/main/java/nbbang/com/nbbang/domain/party/service/PartyWishlistService.java, src/main/java/nbbang/com/nbbang/domain/partymember/controller/PartyMemberController.java, src/main/java/nbbang/com/nbbang/domain/partymember/repository/PartyMemberRepository.java, src/main/java/nbbang/com/nbbang/domain/partymember/service/PartyMemberService.java, src/main/java/nbbang/com/nbbang/global/dto/CursorPageableDto.java, src/main/java/nbbang/com/nbbang/global/dto/PageableDto.java, src/test/java/nbbang/com/nbbang/domain/breadboard/repository/PartyMemberRepositoryTest.java, src/test/java/nbbang/com/nbbang/domain/party/controller/PartyWishlistControllerTest.java, src/test/java/nbbang/com/nbbang/domain/party/service/PartyWishlistServiceTest.java
- 파티 wishlist, exit, join 관련 쿼리를 최적화하였습니다.
=> 파티 wishlist, exit, join 쿼리 최적화
